version: '3.8'

services:
  tmp_vakhrameev:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data/:/data:rw
    environment:
      - DB_PATH=sqlite:////data/database.db
